/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmPhoneNumber
 */
export interface ConfirmPhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof ConfirmPhoneNumber
     */
    token: string;
}

/**
 * Check if a given object implements the ConfirmPhoneNumber interface.
 */
export function instanceOfConfirmPhoneNumber(value: object): boolean {
    if (!('token' in value)) return false;
    return true;
}

export function ConfirmPhoneNumberFromJSON(json: any): ConfirmPhoneNumber {
    return ConfirmPhoneNumberFromJSONTyped(json, false);
}

export function ConfirmPhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPhoneNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ConfirmPhoneNumberToJSON(value?: ConfirmPhoneNumber | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

