/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmEmail
 */
export interface ConfirmEmail {
    /**
     * 
     * @type {string}
     * @memberof ConfirmEmail
     */
    token: string;
}

/**
 * Check if a given object implements the ConfirmEmail interface.
 */
export function instanceOfConfirmEmail(value: object): boolean {
    if (!('token' in value)) return false;
    return true;
}

export function ConfirmEmailFromJSON(json: any): ConfirmEmail {
    return ConfirmEmailFromJSONTyped(json, false);
}

export function ConfirmEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ConfirmEmailToJSON(value?: ConfirmEmail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

