/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmPhoneNumber
 */
export interface ConfirmPhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof ConfirmPhoneNumber
     */
    token: string;
}

/**
 * Check if a given object implements the ConfirmPhoneNumber interface.
 */
export function instanceOfConfirmPhoneNumber(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function ConfirmPhoneNumberFromJSON(json: any): ConfirmPhoneNumber {
    return ConfirmPhoneNumberFromJSONTyped(json, false);
}

export function ConfirmPhoneNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPhoneNumber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ConfirmPhoneNumberToJSON(value?: ConfirmPhoneNumber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

