/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEmail
 */
export interface CreateEmail {
    /**
     * 
     * @type {string}
     * @memberof CreateEmail
     */
    email: string;
}

/**
 * Check if a given object implements the CreateEmail interface.
 */
export function instanceOfCreateEmail(value: object): boolean {
    if (!('email' in value)) return false;
    return true;
}

export function CreateEmailFromJSON(json: any): CreateEmail {
    return CreateEmailFromJSONTyped(json, false);
}

export function CreateEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function CreateEmailToJSON(value?: CreateEmail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

