/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePermission
 */
export interface CreatePermission {
    /**
     * 
     * @type {string}
     * @memberof CreatePermission
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePermission
     */
    uri: string;
}

/**
 * Check if a given object implements the CreatePermission interface.
 */
export function instanceOfCreatePermission(value: object): boolean {
    if (!('description' in value)) return false;
    if (!('uri' in value)) return false;
    return true;
}

export function CreatePermissionFromJSON(json: any): CreatePermission {
    return CreatePermissionFromJSONTyped(json, false);
}

export function CreatePermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePermission {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'uri': json['uri'],
    };
}

export function CreatePermissionToJSON(value?: CreatePermission | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'uri': value['uri'],
    };
}

