/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApplication
 */
export interface CreateApplication {
    /**
     * 
     * @type {string}
     * @memberof CreateApplication
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApplication
     */
    public_url: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateApplication
     */
    signup_enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateApplication
     */
    signup_password?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateApplication
     */
    uri: string;
}

/**
 * Check if a given object implements the CreateApplication interface.
 */
export function instanceOfCreateApplication(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "public_url" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function CreateApplicationFromJSON(json: any): CreateApplication {
    return CreateApplicationFromJSONTyped(json, false);
}

export function CreateApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'public_url': json['public_url'],
        'signup_enabled': !exists(json, 'signup_enabled') ? undefined : json['signup_enabled'],
        'signup_password': !exists(json, 'signup_password') ? undefined : json['signup_password'],
        'uri': json['uri'],
    };
}

export function CreateApplicationToJSON(value?: CreateApplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'public_url': value.public_url,
        'signup_enabled': value.signup_enabled,
        'signup_password': value.signup_password,
        'uri': value.uri,
    };
}

