/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApplicationPermission
 */
export interface CreateApplicationPermission {
    /**
     * 
     * @type {string}
     * @memberof CreateApplicationPermission
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApplicationPermission
     */
    uri: string;
}

/**
 * Check if a given object implements the CreateApplicationPermission interface.
 */
export function instanceOfCreateApplicationPermission(value: object): boolean {
    if (!('description' in value)) return false;
    if (!('uri' in value)) return false;
    return true;
}

export function CreateApplicationPermissionFromJSON(json: any): CreateApplicationPermission {
    return CreateApplicationPermissionFromJSONTyped(json, false);
}

export function CreateApplicationPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApplicationPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'uri': json['uri'],
    };
}

export function CreateApplicationPermissionToJSON(value?: CreateApplicationPermission | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'uri': value['uri'],
    };
}

