/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * 
     * @type {number}
     * @memberof Email
     */
    application_id: number;
    /**
     * 
     * @type {boolean}
     * @memberof Email
     */
    confirmed: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    email: string;
    /**
     * 
     * @type {number}
     * @memberof Email
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    updated_at: Date;
}

/**
 * Check if a given object implements the Email interface.
 */
export function instanceOfEmail(value: object): boolean {
    if (!('application_id' in value)) return false;
    if (!('confirmed' in value)) return false;
    if (!('created_at' in value)) return false;
    if (!('email' in value)) return false;
    if (!('id' in value)) return false;
    if (!('updated_at' in value)) return false;
    return true;
}

export function EmailFromJSON(json: any): Email {
    return EmailFromJSONTyped(json, false);
}

export function EmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): Email {
    if (json == null) {
        return json;
    }
    return {
        
        'application_id': json['application_id'],
        'confirmed': json['confirmed'],
        'created_at': (new Date(json['created_at'])),
        'email': json['email'],
        'id': json['id'],
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function EmailToJSON(value?: Email | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'application_id': value['application_id'],
        'confirmed': value['confirmed'],
        'created_at': ((value['created_at']).toISOString()),
        'email': value['email'],
        'id': value['id'],
        'updated_at': ((value['updated_at']).toISOString()),
    };
}

