/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface Errors
 */
export interface Errors {
    /**
     * 
     * @type {{ [key: string]: Array<ErrorMessage>; }}
     * @memberof Errors
     */
    errors: { [key: string]: Array<ErrorMessage>; };
}

/**
 * Check if a given object implements the Errors interface.
 */
export function instanceOfErrors(value: object): boolean {
    if (!('errors' in value)) return false;
    return true;
}

export function ErrorsFromJSON(json: any): Errors {
    return ErrorsFromJSONTyped(json, false);
}

export function ErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Errors {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'],
    };
}

export function ErrorsToJSON(value?: Errors | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errors': value['errors'],
    };
}

