/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelApplicationConfigSTSignupPassword } from './ModelApplicationConfigSTSignupPassword';
import {
    ModelApplicationConfigSTSignupPasswordFromJSON,
    ModelApplicationConfigSTSignupPasswordFromJSONTyped,
    ModelApplicationConfigSTSignupPasswordToJSON,
} from './ModelApplicationConfigSTSignupPassword';

/**
 * 
 * @export
 * @interface ModelApplicationConfigSTSignup
 */
export interface ModelApplicationConfigSTSignup {
    /**
     * 
     * @type {boolean}
     * @memberof ModelApplicationConfigSTSignup
     */
    enabled?: boolean;
    /**
     * 
     * @type {ModelApplicationConfigSTSignupPassword}
     * @memberof ModelApplicationConfigSTSignup
     */
    password?: ModelApplicationConfigSTSignupPassword;
}

/**
 * Check if a given object implements the ModelApplicationConfigSTSignup interface.
 */
export function instanceOfModelApplicationConfigSTSignup(value: object): boolean {
    return true;
}

export function ModelApplicationConfigSTSignupFromJSON(json: any): ModelApplicationConfigSTSignup {
    return ModelApplicationConfigSTSignupFromJSONTyped(json, false);
}

export function ModelApplicationConfigSTSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApplicationConfigSTSignup {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'password': json['password'] == null ? undefined : ModelApplicationConfigSTSignupPasswordFromJSON(json['password']),
    };
}

export function ModelApplicationConfigSTSignupToJSON(value?: ModelApplicationConfigSTSignup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': value['enabled'],
        'password': ModelApplicationConfigSTSignupPasswordToJSON(value['password']),
    };
}

