/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelApplicationConfigSTSignup } from './ModelApplicationConfigSTSignup';
import {
    ModelApplicationConfigSTSignupFromJSON,
    ModelApplicationConfigSTSignupFromJSONTyped,
    ModelApplicationConfigSTSignupToJSON,
} from './ModelApplicationConfigSTSignup';

/**
 * 
 * @export
 * @interface ModelApplicationConfigST
 */
export interface ModelApplicationConfigST {
    /**
     * 
     * @type {ModelApplicationConfigSTSignup}
     * @memberof ModelApplicationConfigST
     */
    signup?: ModelApplicationConfigSTSignup;
}

/**
 * Check if a given object implements the ModelApplicationConfigST interface.
 */
export function instanceOfModelApplicationConfigST(value: object): boolean {
    return true;
}

export function ModelApplicationConfigSTFromJSON(json: any): ModelApplicationConfigST {
    return ModelApplicationConfigSTFromJSONTyped(json, false);
}

export function ModelApplicationConfigSTFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApplicationConfigST {
    if (json == null) {
        return json;
    }
    return {
        
        'signup': json['signup'] == null ? undefined : ModelApplicationConfigSTSignupFromJSON(json['signup']),
    };
}

export function ModelApplicationConfigSTToJSON(value?: ModelApplicationConfigST | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'signup': ModelApplicationConfigSTSignupToJSON(value['signup']),
    };
}

