/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelApplicationConfigSTSignupPassword
 */
export interface ModelApplicationConfigSTSignupPassword {
    /**
     * 
     * @type {boolean}
     * @memberof ModelApplicationConfigSTSignupPassword
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the ModelApplicationConfigSTSignupPassword interface.
 */
export function instanceOfModelApplicationConfigSTSignupPassword(value: object): boolean {
    return true;
}

export function ModelApplicationConfigSTSignupPasswordFromJSON(json: any): ModelApplicationConfigSTSignupPassword {
    return ModelApplicationConfigSTSignupPasswordFromJSONTyped(json, false);
}

export function ModelApplicationConfigSTSignupPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelApplicationConfigSTSignupPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function ModelApplicationConfigSTSignupPasswordToJSON(value?: ModelApplicationConfigSTSignupPassword | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': value['enabled'],
    };
}

