/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApplicationTenent } from './ApplicationTenent';
import {
    ApplicationTenentFromJSON,
    ApplicationTenentFromJSONTyped,
    ApplicationTenentToJSON,
} from './ApplicationTenent';

/**
 * 
 * @export
 * @interface PaginationApplicationTenent
 */
export interface PaginationApplicationTenent {
    /**
     * 
     * @type {boolean}
     * @memberof PaginationApplicationTenent
     */
    has_more: boolean;
    /**
     * 
     * @type {Array<ApplicationTenent>}
     * @memberof PaginationApplicationTenent
     */
    items: Array<ApplicationTenent>;
}

/**
 * Check if a given object implements the PaginationApplicationTenent interface.
 */
export function instanceOfPaginationApplicationTenent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "has_more" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function PaginationApplicationTenentFromJSON(json: any): PaginationApplicationTenent {
    return PaginationApplicationTenentFromJSONTyped(json, false);
}

export function PaginationApplicationTenentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationApplicationTenent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'has_more': json['has_more'],
        'items': ((json['items'] as Array<any>).map(ApplicationTenentFromJSON)),
    };
}

export function PaginationApplicationTenentToJSON(value?: PaginationApplicationTenent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'has_more': value.has_more,
        'items': ((value.items as Array<any>).map(ApplicationTenentToJSON)),
    };
}

