/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPassword
 */
export interface ResetPassword {
    /**
     * 
     * @type {string}
     * @memberof ResetPassword
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPassword
     */
    password_confirmation: string;
}

/**
 * Check if a given object implements the ResetPassword interface.
 */
export function instanceOfResetPassword(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "password_confirmation" in value;

    return isInstance;
}

export function ResetPasswordFromJSON(json: any): ResetPassword {
    return ResetPasswordFromJSONTyped(json, false);
}

export function ResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPassword {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'password_confirmation': json['password_confirmation'],
    };
}

export function ResetPasswordToJSON(value?: ResetPassword | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'password_confirmation': value.password_confirmation,
    };
}

