/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfoAddress } from './UserInfoAddress';
import {
    UserInfoAddressFromJSON,
    UserInfoAddressFromJSONTyped,
    UserInfoAddressToJSON,
} from './UserInfoAddress';

/**
 * 
 * @export
 * @interface UpdateUserInfoRequest
 */
export interface UpdateUserInfoRequest {
    /**
     * 
     * @type {UserInfoAddress}
     * @memberof UpdateUserInfoRequest
     */
    address?: UserInfoAddress;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    birthdate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    family_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    given_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    middle_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    picture?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    profile?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    zoneinfo?: string;
}

/**
 * Check if a given object implements the UpdateUserInfoRequest interface.
 */
export function instanceOfUpdateUserInfoRequest(value: object): boolean {
    return true;
}

export function UpdateUserInfoRequestFromJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestFromJSONTyped(json, false);
}

export function UpdateUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : UserInfoAddressFromJSON(json['address']),
        'birthdate': json['birthdate'] == null ? undefined : json['birthdate'],
        'family_name': json['family_name'] == null ? undefined : json['family_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'given_name': json['given_name'] == null ? undefined : json['given_name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'middle_name': json['middle_name'] == null ? undefined : json['middle_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'website': json['website'] == null ? undefined : json['website'],
        'zoneinfo': json['zoneinfo'] == null ? undefined : json['zoneinfo'],
    };
}

export function UpdateUserInfoRequestToJSON(value?: UpdateUserInfoRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': UserInfoAddressToJSON(value['address']),
        'birthdate': value['birthdate'],
        'family_name': value['family_name'],
        'gender': value['gender'],
        'given_name': value['given_name'],
        'locale': value['locale'],
        'middle_name': value['middle_name'],
        'name': value['name'],
        'nickname': value['nickname'],
        'picture': value['picture'],
        'profile': value['profile'],
        'website': value['website'],
        'zoneinfo': value['zoneinfo'],
    };
}

