/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationPermission
 */
export interface UpdateApplicationPermission {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationPermission
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationPermission
     */
    uri?: string;
}

/**
 * Check if a given object implements the UpdateApplicationPermission interface.
 */
export function instanceOfUpdateApplicationPermission(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateApplicationPermissionFromJSON(json: any): UpdateApplicationPermission {
    return UpdateApplicationPermissionFromJSONTyped(json, false);
}

export function UpdateApplicationPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationPermission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function UpdateApplicationPermissionToJSON(value?: UpdateApplicationPermission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'uri': value.uri,
    };
}

