/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationTenent
 */
export interface UpdateApplicationTenent {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    algorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    client_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateApplicationTenent
     */
    expires_in_seconds?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    private_key?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    public_key?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateApplicationTenent
     */
    refresh_expires_in_seconds?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    uri: string;
}

/**
 * Check if a given object implements the UpdateApplicationTenent interface.
 */
export function instanceOfUpdateApplicationTenent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function UpdateApplicationTenentFromJSON(json: any): UpdateApplicationTenent {
    return UpdateApplicationTenentFromJSONTyped(json, false);
}

export function UpdateApplicationTenentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationTenent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'algorithm': !exists(json, 'algorithm') ? undefined : json['algorithm'],
        'client_id': !exists(json, 'client_id') ? undefined : json['client_id'],
        'description': json['description'],
        'expires_in_seconds': !exists(json, 'expires_in_seconds') ? undefined : json['expires_in_seconds'],
        'private_key': !exists(json, 'private_key') ? undefined : json['private_key'],
        'public_key': !exists(json, 'public_key') ? undefined : json['public_key'],
        'refresh_expires_in_seconds': !exists(json, 'refresh_expires_in_seconds') ? undefined : json['refresh_expires_in_seconds'],
        'uri': json['uri'],
    };
}

export function UpdateApplicationTenentToJSON(value?: UpdateApplicationTenent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'algorithm': value.algorithm,
        'client_id': value.client_id,
        'description': value.description,
        'expires_in_seconds': value.expires_in_seconds,
        'private_key': value.private_key,
        'public_key': value.public_key,
        'refresh_expires_in_seconds': value.refresh_expires_in_seconds,
        'uri': value.uri,
    };
}

