/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserInfoAddress } from './UserInfoAddress';
import {
    UserInfoAddressFromJSON,
    UserInfoAddressFromJSONTyped,
    UserInfoAddressToJSON,
} from './UserInfoAddress';

/**
 * 
 * @export
 * @interface UpdateUserInfoRequest
 */
export interface UpdateUserInfoRequest {
    /**
     * 
     * @type {UserInfoAddress}
     * @memberof UpdateUserInfoRequest
     */
    address?: UserInfoAddress;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    birthdate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    family_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    given_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    middle_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    picture?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    profile?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInfoRequest
     */
    zoneinfo?: string;
}

/**
 * Check if a given object implements the UpdateUserInfoRequest interface.
 */
export function instanceOfUpdateUserInfoRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserInfoRequestFromJSON(json: any): UpdateUserInfoRequest {
    return UpdateUserInfoRequestFromJSONTyped(json, false);
}

export function UpdateUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : UserInfoAddressFromJSON(json['address']),
        'birthdate': !exists(json, 'birthdate') ? undefined : json['birthdate'],
        'family_name': !exists(json, 'family_name') ? undefined : json['family_name'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'given_name': !exists(json, 'given_name') ? undefined : json['given_name'],
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'middle_name': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'profile': !exists(json, 'profile') ? undefined : json['profile'],
        'website': !exists(json, 'website') ? undefined : json['website'],
        'zoneinfo': !exists(json, 'zoneinfo') ? undefined : json['zoneinfo'],
    };
}

export function UpdateUserInfoRequestToJSON(value?: UpdateUserInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': UserInfoAddressToJSON(value.address),
        'birthdate': value.birthdate,
        'family_name': value.family_name,
        'gender': value.gender,
        'given_name': value.given_name,
        'locale': value.locale,
        'middle_name': value.middle_name,
        'name': value.name,
        'nickname': value.nickname,
        'picture': value.picture,
        'profile': value.profile,
        'website': value.website,
        'zoneinfo': value.zoneinfo,
    };
}

