/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplication
 */
export interface UpdateApplication {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplication
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplication
     */
    public_url: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateApplication
     */
    signup_enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateApplication
     */
    signup_password?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplication
     */
    uri?: string;
}

/**
 * Check if a given object implements the UpdateApplication interface.
 */
export function instanceOfUpdateApplication(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "public_url" in value;

    return isInstance;
}

export function UpdateApplicationFromJSON(json: any): UpdateApplication {
    return UpdateApplicationFromJSONTyped(json, false);
}

export function UpdateApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'public_url': json['public_url'],
        'signup_enabled': !exists(json, 'signup_enabled') ? undefined : json['signup_enabled'],
        'signup_password': !exists(json, 'signup_password') ? undefined : json['signup_password'],
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function UpdateApplicationToJSON(value?: UpdateApplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'public_url': value.public_url,
        'signup_enabled': value.signup_enabled,
        'signup_password': value.signup_password,
        'uri': value.uri,
    };
}

