/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationTenent
 */
export interface UpdateApplicationTenent {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    algorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    client_id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateApplicationTenent
     */
    expires_in_seconds?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    private_key?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    public_key?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateApplicationTenent
     */
    refresh_expires_in_seconds?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationTenent
     */
    uri: string;
}

/**
 * Check if a given object implements the UpdateApplicationTenent interface.
 */
export function instanceOfUpdateApplicationTenent(value: object): boolean {
    if (!('description' in value)) return false;
    if (!('uri' in value)) return false;
    return true;
}

export function UpdateApplicationTenentFromJSON(json: any): UpdateApplicationTenent {
    return UpdateApplicationTenentFromJSONTyped(json, false);
}

export function UpdateApplicationTenentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationTenent {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : json['algorithm'],
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'description': json['description'],
        'expires_in_seconds': json['expires_in_seconds'] == null ? undefined : json['expires_in_seconds'],
        'private_key': json['private_key'] == null ? undefined : json['private_key'],
        'public_key': json['public_key'] == null ? undefined : json['public_key'],
        'refresh_expires_in_seconds': json['refresh_expires_in_seconds'] == null ? undefined : json['refresh_expires_in_seconds'],
        'uri': json['uri'],
    };
}

export function UpdateApplicationTenentToJSON(value?: UpdateApplicationTenent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'algorithm': value['algorithm'],
        'client_id': value['client_id'],
        'description': value['description'],
        'expires_in_seconds': value['expires_in_seconds'],
        'private_key': value['private_key'],
        'public_key': value['public_key'],
        'refresh_expires_in_seconds': value['refresh_expires_in_seconds'],
        'uri': value['uri'],
    };
}

