/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';
import type { PhoneNumber } from './PhoneNumber';
import {
    PhoneNumberFromJSON,
    PhoneNumberFromJSONTyped,
    PhoneNumberToJSON,
} from './PhoneNumber';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    created_at: Date;
    /**
     * 
     * @type {Email}
     * @memberof User
     */
    email?: Email;
    /**
     * 
     * @type {Array<Email>}
     * @memberof User
     */
    emails: Array<Email>;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof User
     */
    phone_number?: PhoneNumber;
    /**
     * 
     * @type {Array<PhoneNumber>}
     * @memberof User
     */
    phone_numbers: Array<PhoneNumber>;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updated_at: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    if (!('created_at' in value)) return false;
    if (!('emails' in value)) return false;
    if (!('id' in value)) return false;
    if (!('phone_numbers' in value)) return false;
    if (!('updated_at' in value)) return false;
    if (!('username' in value)) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'email': json['email'] == null ? undefined : EmailFromJSON(json['email']),
        'emails': ((json['emails'] as Array<any>).map(EmailFromJSON)),
        'id': json['id'],
        'phone_number': json['phone_number'] == null ? undefined : PhoneNumberFromJSON(json['phone_number']),
        'phone_numbers': ((json['phone_numbers'] as Array<any>).map(PhoneNumberFromJSON)),
        'updated_at': (new Date(json['updated_at'])),
        'username': json['username'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['created_at']).toISOString()),
        'email': EmailToJSON(value['email']),
        'emails': ((value['emails'] as Array<any>).map(EmailToJSON)),
        'id': value['id'],
        'phone_number': PhoneNumberToJSON(value['phone_number']),
        'phone_numbers': ((value['phone_numbers'] as Array<any>).map(PhoneNumberToJSON)),
        'updated_at': ((value['updated_at']).toISOString()),
        'username': value['username'],
    };
}

