/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfoAddress } from './UserInfoAddress';
import {
    UserInfoAddressFromJSON,
    UserInfoAddressFromJSONTyped,
    UserInfoAddressToJSON,
} from './UserInfoAddress';

/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {UserInfoAddress}
     * @memberof UserInfo
     */
    address?: UserInfoAddress;
    /**
     * 
     * @type {Date}
     * @memberof UserInfo
     */
    birthdate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserInfo
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    family_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    given_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    middle_name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    picture?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    preferred_username: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    profile?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserInfo
     */
    updated_at: Date;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    user_id: number;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    zoneinfo?: string;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): boolean {
    if (!('created_at' in value)) return false;
    if (!('preferred_username' in value)) return false;
    if (!('updated_at' in value)) return false;
    if (!('user_id' in value)) return false;
    return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
    return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : UserInfoAddressFromJSON(json['address']),
        'birthdate': json['birthdate'] == null ? undefined : (new Date(json['birthdate'])),
        'created_at': (new Date(json['created_at'])),
        'family_name': json['family_name'] == null ? undefined : json['family_name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'given_name': json['given_name'] == null ? undefined : json['given_name'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'middle_name': json['middle_name'] == null ? undefined : json['middle_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'preferred_username': json['preferred_username'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'updated_at': (new Date(json['updated_at'])),
        'user_id': json['user_id'],
        'website': json['website'] == null ? undefined : json['website'],
        'zoneinfo': json['zoneinfo'] == null ? undefined : json['zoneinfo'],
    };
}

export function UserInfoToJSON(value?: UserInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': UserInfoAddressToJSON(value['address']),
        'birthdate': value['birthdate'] == null ? undefined : ((value['birthdate']).toISOString()),
        'created_at': ((value['created_at']).toISOString()),
        'family_name': value['family_name'],
        'gender': value['gender'],
        'given_name': value['given_name'],
        'locale': value['locale'],
        'middle_name': value['middle_name'],
        'name': value['name'],
        'nickname': value['nickname'],
        'picture': value['picture'],
        'preferred_username': value['preferred_username'],
        'profile': value['profile'],
        'updated_at': ((value['updated_at']).toISOString()),
        'user_id': value['user_id'],
        'website': value['website'],
        'zoneinfo': value['zoneinfo'],
    };
}

