/* tslint:disable */
/* eslint-disable */
/**
 * Auth API
 * Auth API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Token,
  TokenRequest,
} from '../models/index';
import {
    TokenFromJSON,
    TokenToJSON,
    TokenRequestFromJSON,
    TokenRequestToJSON,
} from '../models/index';

export interface TokenPostRequest {
    tokenRequest: TokenRequest;
}

/**
 * TokenApi - interface
 * 
 * @export
 * @interface TokenApiInterface
 */
export interface TokenApiInterface {
    /**
     * 
     * @summary Create JWT Token
     * @param {TokenRequest} tokenRequest token request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApiInterface
     */
    tokenPostRaw(requestParameters: TokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>>;

    /**
     * Create JWT Token
     */
    tokenPost(tokenRequest: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token>;

}

/**
 * 
 */
export class TokenApi extends runtime.BaseAPI implements TokenApiInterface {

    /**
     * Create JWT Token
     */
    async tokenPostRaw(requestParameters: TokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters.tokenRequest === null || requestParameters.tokenRequest === undefined) {
            throw new runtime.RequiredError('tokenRequest','Required parameter requestParameters.tokenRequest was null or undefined when calling tokenPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Tenent-Id"] = this.configuration.apiKey("Tenent-Id"); // ApplicationTenentId authentication
        }

        const response = await this.request({
            path: `/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRequestToJSON(requestParameters.tokenRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Create JWT Token
     */
    async tokenPost(tokenRequest: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.tokenPostRaw({ tokenRequest: tokenRequest }, initOverrides);
        return await response.value();
    }

}
