// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​i​g​n​ ​i​n
	 */
	sign_in: string
	/**
	 * S​i​g​n​ ​u​p
	 */
	sign_up: string
	/**
	 * N​o​t​ ​a​ ​m​e​m​b​e​r​?
	 */
	not_a_member: string
	/**
	 * A​l​r​e​a​d​y​ ​a​ ​m​e​m​b​e​r​?
	 */
	already_a_member: string
	/**
	 * U​s​e​r​n​a​m​e​/​E​m​a​i​l
	 */
	username_placeholder: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password_placeholder: string
}

export type TranslationFunctions = {
	/**
	 * Sign in
	 */
	sign_in: () => LocalizedString
	/**
	 * Sign up
	 */
	sign_up: () => LocalizedString
	/**
	 * Not a member?
	 */
	not_a_member: () => LocalizedString
	/**
	 * Already a member?
	 */
	already_a_member: () => LocalizedString
	/**
	 * Username/Email
	 */
	username_placeholder: () => LocalizedString
	/**
	 * Password
	 */
	password_placeholder: () => LocalizedString
}

export type Formatters = {}
