apiVersion: v1
kind: Service
metadata:
  name: {{ include "aicacia-auth_ui.fullname" . }}
  labels: {{- include "aicacia-auth_ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "aicacia-auth_ui.selectorLabels" . | nindent 4 }}
